import { VideoType } from "~/type/video-type";

export const diverseVideos: VideoType[] = [
  { code: "nQ0maWdpMEM" },
  { code: "-Ym4PgTJpPI" },
  { code: "Fv8WzscKKBU" },
  { code: "ha5vhjHN7hE" },
  { code: "uugiHIu99FM" },
  { code: "GTOLVPZyiwE" },
  { code: "JR4V2KUVHxI" },
  { code: "ZIXExdjvNv8" },
  { code: "AmCZTWmMn9c" },
  { code: "GrOhsvz5ZuM" },
  { code: "WLc9HMFYBzc" },
  { code: "DDkM0am0k_0" },
  { code: "HO4GaRK4NKo" },
  { code: "UUlaseGrkLc", description: "nice" },
  { code: "1P3ZgLOy-w8", description: "tartaruga" },
  { code: "kQjtK32mGJQ", description: "work work work" },
  { code: "4qCbiCxBd2M", description: "blind girl" },
  { code: "6YSxJnqCr8I", description: "snack attack" },
  { code: "Hrph2EW9VjY" },
  { code: "pVHKp6ffURY" },
  { code: "cvvd-9azD1M" },
  { code: "1V_xRb0x9aw" },
  { code: "l6rS8Dv5g-8" },
  { code: "l6rS8Dv5g-8" },
  { code: "MsXdUtlDVhk" },
  { code: "ZyhrYis509A" },
  { code: "r2LVJU6Qnkc" },
  { code: "9Wzr9EK47_U" },
  { code: "GibiNy4d4gc" },
  { code: "vP9r6UjCA7I" },
  { code: "uw5ajQ_ya0s" },
  { code: "ZXcTvbLwsRs" },
  { code: "DieDbDmNXE4" },
];
